name:                jmonkey-example

executables:
  jmonkey-example-exe:
    main:                Main.hs
    source-dirs:         web
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base >= 4.7 && < 5
    - jmonkey
    - lucid
    - clay
    - warp
    - wai
    - http-types
    - text
    - casing
